stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests..."
    # Aggiungi qui i tuoi comandi di test

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    # Aggiungi qui i tuoi comandi di deploy
